### ISSUE TITLE
Asside element markup and styling

### ISSUE THREAD

**Issue by pavelbidenko2018** [fmkarakus/pair-integrate#6]
### Repository

1. This user story was developed locally by Pavel on a brach called `references`.
2. The new branch was pushed to the shared repository
3. A pull request was made to `master` & reviewed by the team
4. Changes were merged to `master`

### HTML

- aside element
- some links for people to learn more about the cool thing

### CSS

Styling for the new element

---

**Comment by pavelbidenko2018** [comment]
close #6

**Comment by snicoll** [comment]
Commit 5a60280ebcda34f3 does not really close this one right? It was 
b76200f that was polished by 5a60280. If you've missed the closes instruction that's ok, just close the issue manually. If you have extra commit that polishes things up, it should states so. 

A commit message is a way for the team to understand what was changed and why. Reference to issues help providing additional context.
